<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerIPZ66nh\srcApp_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerIPZ66nh/srcApp_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerIPZ66nh.legacy');

    return;
}

if (!\class_exists(srcApp_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerIPZ66nh\srcApp_KernelDevDebugContainer::class, srcApp_KernelDevDebugContainer::class, false);
}

return new \ContainerIPZ66nh\srcApp_KernelDevDebugContainer([
    'container.build_hash' => 'IPZ66nh',
    'container.build_id' => 'e253d724',
    'container.build_time' => 1635313740,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerIPZ66nh');
